### ISSUE TITLE
Python 3.6  and Django 2.1?

### ISSUE THREAD

**Issue by matt-bradley** [redzej/graphene-permissions#19] opened 2018-08-28 13:47 UTC
Latest version seems to be rolling my Django Version back to 1.11

**Comment by redzej** [comment] 2018-08-28 17:11
Hello, are you sure that the problem is with django, not django-filter? Django version is not frozen in package, but django-filter had to due to this issue in graphene itself: https://github.com/graphql-python/graphene-django/issues/464
Anyway, Django 2.1 is not available too atm, but versions 2.0.* seems to work.

**Comment by redzej** [comment] 2018-09-04 23:10
Hi @matt-bradley, i was not able to reproduce bug, other than newest django-filter and graphene incompatibility. New version of this package will come out in ~2 weeks, so i'm going to close this issue.

**Comment by redzej** [comment] 2018-11-19 20:20
@matt-bradley PR #20 should fix this issue if that was django-filter problem, package itself requires at least Django 2.0.

**Closed as completed by redzej** 2018-11-19 20:20 UTC
Labels: bug, high-priorty
